''' Output of Chronicle's METADATA for an mkv file (shows up with chapter timestamps in potplayer)
C:\\Users\\user\\Downloads\\_Tor\\Chronicle.2012.Director.s.Cut.iTA.ENG.AC3.SUB.iTA.ENG.BluRay.1080p.x264.jeddak-MIRCrew.mkv
'''


{
    'streams': [
        {
            'index': 0,
            'codec_name': 'h264',
            'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
            'profile': 'High',
            'codec_type': 'video',
            'codec_time_base': '1001/48000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'width': 1920,
            'height': 1040,
            'has_b_frames': 2,
            'sample_aspect_ratio': '1:1',
            'display_aspect_ratio': '24:13',
            'pix_fmt': 'yuv420p',
            'level': 41,
            'r_frame_rate': '24000/1001',
            'avg_frame_rate': '24000/1001',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'title': '...::: jeddak MIRCrew :::...', 'DURATION': '01:29:36.418000000'}
        },
        {
            'index': 1,
            'codec_name': 'ac3',
            'codec_long_name': 'ATSC A/52A (AC-3)',
            'codec_type': 'audio',
            'codec_time_base': '1/48000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'sample_fmt': 'fltp',
            'sample_rate': '48000',
            'channels': 6,
            'bits_per_sample': 0,
            'dmix_mode': '-1',
            'ltrt_cmixlev': '-1.000000',
            'ltrt_surmixlev': '-1.000000',
            'loro_cmixlev': '-1.000000',
            'loro_surmixlev': '-1.000000',
            'r_frame_rate': '0/0',
            'avg_frame_rate': '0/0',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'bit_rate': '448000',
            'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'language': 'ita', 'title': 'iTA AC3 5.1', 'DURATION': '01:29:36.448000000'}
        },
        {
            'index': 2,
            'codec_name': 'ac3',
            'codec_long_name': 'ATSC A/52A (AC-3)',
            'codec_type': 'audio',
            'codec_time_base': '1/48000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'sample_fmt': 'fltp',
            'sample_rate': '48000',
            'channels': 6,
            'bits_per_sample': 0,
            'dmix_mode': '-1',
            'ltrt_cmixlev': '-1.000000',
            'ltrt_surmixlev': '-1.000000',
            'loro_cmixlev': '-1.000000',
            'loro_surmixlev': '-1.000000',
            'r_frame_rate': '0/0',
            'avg_frame_rate': '0/0',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'bit_rate': '448000',
            'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'language': 'eng', 'title': 'ENG AC3 5.1', 'DURATION': '01:29:36.448000000'}
        },
        {
            'index': 3,
            'codec_name': 'subrip',
            'codec_long_name': 'SubRip subtitle',
            'codec_type': 'subtitle',
            'codec_time_base': '1/1000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'r_frame_rate': '0/0',
            'avg_frame_rate': '0/0',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 1, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'language': 'ita', 'title': 'iTA FORCED - SRT'}
        },
        {
            'index': 4,
            'codec_name': 'pgssub',
            'codec_long_name': 'HDMV Presentation Graphic Stream subtitles',
            'codec_type': 'subtitle',
            'codec_time_base': '1/1000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'r_frame_rate': '0/0',
            'avg_frame_rate': '0/0',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 1, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'language': 'ita', 'title': 'iTA FORCED - PGS', 'DURATION': '01:29:31.033000000'}
        },
        {
            'index': 5,
            'codec_name': 'pgssub',
            'codec_long_name': 'HDMV Presentation Graphic Stream subtitles',
            'codec_type': 'subtitle',
            'codec_time_base': '1/1000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'r_frame_rate': '0/0',
            'avg_frame_rate': '0/0',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'language': 'ita', 'title': 'iTA REGULAR - PGS', 'DURATION': '01:29:31.033000000'}
        },
        {
            'index': 6,
            'codec_name': 'pgssub',
            'codec_long_name': 'HDMV Presentation Graphic Stream subtitles',
            'codec_type': 'subtitle',
            'codec_time_base': '1/1000',
            'codec_tag_string': '[0][0][0][0]',
            'codec_tag': '0x0000',
            'r_frame_rate': '0/0',
            'avg_frame_rate': '0/0',
            'time_base': '1/1000',
            'start_pts': 0,
            'start_time': '0.000000',
            'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0},
            'tags': {'language': 'eng', 'title': 'ENG REGULAR - PGS', 'DURATION': '01:29:31.033000000'}
        }
    ],
    'format': {
        'filename': 'C:\\Users\\user\\Downloads\\_Tor\\Chronicle.2012.Director.s.Cut.iTA.ENG.AC3.SUB.iTA.ENG.BluRay.1080p.x264.jeddak-MIRCrew.mkv',
        'nb_streams': 7,
        'nb_programs': 0,
        'format_name': 'matroska,webm',
        'format_long_name': 'Matroska / WebM',
        'start_time': '0.000000',
        'duration': '5376.448000',
        'size': '2272002570',
        'bit_rate': '3380674',
        'tags': {'title': 'Chronicle.2012.Director.s.Cut.iTA.ENG.AC3.SUB.iTA.ENG.BluRay.1080p.x264.jeddak-MIRCrew', 'creation_time': '2024-10-09 06:45:34', 'ENCODER': 'Lavf58.76.100'}
    }
}