pt(series, video_based_frame_sequences, video_paths, frame_based_results) Length: 4 variables (Line :323, @test_marking_of_videos(), mark_videos.py) - 
    >1>  series: (1 elements below) pt.size = 62 Bytes (estimated) - dict, Length: 1, (Line :323, @test_marking_of_videos(), mark_videos.py)
       >  {'3_complete_vids_to_test': {'3_complete_vids_to_test': ['C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e01_40.mp4',
       >  'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e02_40.mp4', 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e03_40.mp4',
       >  'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e04_40.mp4', 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\aa.mp4']}}
    ^ ^ ^ pt(series): (1 elements above this) pt.size = 62 Bytes (estimated) - dict, Length: 1, (Line :323, @test_marking_of_videos(), mark_videos.py)
    >2>  video_based_frame_sequences: (4 elements below) pt.size = 62 Bytes (estimated) - dict, Length: 4, (Line :323, @test_marking_of_videos(), mark_videos.py)
       >  {'_s01e01_40.mp4': {'sequence 0': [2, 16], 'sequence 1': [34, 39], 'sequence 2': [25, 29], 'sequence 3': [43, 47], 'sequence 4': [52, 56], 'sequence 5': [65, 69], 'sequence 6': [74, 78], 'sequence 7': [80, 94]}, '_s01e02_40.mp4': {'sequence 0': [2, 16], 'sequence 1': [21,
       >  23], 'sequence 2': [35, 39], 'sequence 3': [26, 30], 'sequence 4': [43, 48], 'sequence 5': [53, 57], 'sequence 6': [66, 70], 'sequence 7': [74, 91]}, '_s01e03_40.mp4': {'sequence 0': [3, 17], 'sequence 1': [22, 24], 'sequence 2': [36, 40], 'sequence 3': [27, 31],
       >  'sequence 4': [44, 48], 'sequence 5': [53, 57], 'sequence 6': [66, 70], 'sequence 7': [90, 94], 'sequence 8': [73, 87]}, '_s01e04_40.mp4': {'sequence 0': [4, 18], 'sequence 1': [23, 24], 'sequence 2': [37, 41], 'sequence 3': [28, 32], 'sequence 4': [45, 49], 'sequence 5':
       >  [54, 58], 'sequence 6': [67, 86], 'sequence 7': [90, 94]}}
    ^ ^ ^ pt(video_based_frame_sequences): (4 elements above this) pt.size = 62 Bytes (estimated) - dict, Length: 4, (Line :323, @test_marking_of_videos(), mark_videos.py)
    >3>  video_paths: (5 elements below) pt.size = 62 Bytes (estimated) - dict, Length: 5, (Line :323, @test_marking_of_videos(), mark_videos.py)
       >  {'_s01e01_40.mp4': 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e01_40.mp4', '_s01e02_40.mp4':
       >  'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e02_40.mp4', '_s01e03_40.mp4': 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e03_40.mp4',
       >  '_s01e04_40.mp4': 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\_s01e04_40.mp4', 'aa.mp4':
       >  'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\aa.mp4'}
    ^ ^ ^ pt(video_paths): (5 elements above this) pt.size = 62 Bytes (estimated) - dict, Length: 5, (Line :323, @test_marking_of_videos(), mark_videos.py)
    >4>  frame_based_results: (4 elements below) pt.size = 62 Bytes (estimated) - list, Length: 4, (Line :323, @test_marking_of_videos(), mark_videos.py)
       >  [{'video_name': '_s01e01_40.mp4', 'output_path': 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\marked__s01e01_40.mkv', 'updated_chapters': [{'EDITION_FLAG_ORDERED': '1', 'TIMEBASE': '1/1000', 'START': '2',
       >  'END': '16', 'title': '__cut_frames_1', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '25', 'END': '29', 'title': '__cut_frames_3', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '34', 'END': '39', 'title': '__cut_frames_2', 'enabled': '0',
       >  'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '43', 'END': '47', 'title': '__cut_frames_4', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '52', 'END': '56', 'title': '__cut_frames_5', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '65',
       >  'END': '69', 'title': '__cut_frames_6', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '74', 'END': '78', 'title': '__cut_frames_7', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '80', 'END': '94', 'title': '__cut_frames_8', 'enabled': '0',
       >  'skip': '0'}]}, {'video_name': '_s01e02_40.mp4', 'output_path': 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\marked__s01e02_40.mkv', 'updated_chapters': [{'EDITION_FLAG_ORDERED': '1', 'TIMEBASE': '1/1000',
       >  'START': '2', 'END': '16', 'title': '__cut_frames_1', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '21', 'END': '23', 'title': '__cut_frames_2', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '26', 'END': '30', 'title': '__cut_frames_4',
       >  'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '35', 'END': '39', 'title': '__cut_frames_3', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '43', 'END': '48', 'title': '__cut_frames_5', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000',
       >  'START': '53', 'END': '57', 'title': '__cut_frames_6', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '66', 'END': '70', 'title': '__cut_frames_7', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '74', 'END': '91', 'title': '__cut_frames_8',
       >  'enabled': '0', 'skip': '0'}]}, {'video_name': '_s01e03_40.mp4', 'output_path': 'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\marked__s01e03_40.mkv', 'updated_chapters': [{'EDITION_FLAG_ORDERED': '1',
       >  'TIMEBASE': '1/1000', 'START': '3', 'END': '17', 'title': '__cut_frames_1', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '22', 'END': '24', 'title': '__cut_frames_2', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '27', 'END': '31',
       >  'title': '__cut_frames_4', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '36', 'END': '40', 'title': '__cut_frames_3', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '44', 'END': '48', 'title': '__cut_frames_5', 'enabled': '0', 'skip': '0'},
       >  {'TIMEBASE': '1/1000', 'START': '53', 'END': '57', 'title': '__cut_frames_6', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '66', 'END': '70', 'title': '__cut_frames_7', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '73', 'END': '87',
       >  'title': '__cut_frames_9', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '90', 'END': '94', 'title': '__cut_frames_8', 'enabled': '0', 'skip': '0'}]}, {'video_name': '_s01e04_40.mp4', 'output_path':
       >  'C:\\.PythonProjects\\uve_ultra_videos_entertainment\\videos_for_testing\\tiny_vids\\3_complete_vids_to_test\\marked__s01e04_40.mkv', 'updated_chapters': [{'EDITION_FLAG_ORDERED': '1', 'TIMEBASE': '1/1000', 'START': '4', 'END': '18', 'title': '__cut_frames_1', 'enabled':
       >  '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '23', 'END': '24', 'title': '__cut_frames_2', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '28', 'END': '32', 'title': '__cut_frames_4', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '37',
       >  'END': '41', 'title': '__cut_frames_3', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '45', 'END': '49', 'title': '__cut_frames_5', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '54', 'END': '58', 'title': '__cut_frames_6', 'enabled': '0',
       >  'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '67', 'END': '86', 'title': '__cut_frames_7', 'enabled': '0', 'skip': '0'}, {'TIMEBASE': '1/1000', 'START': '90', 'END': '94', 'title': '__cut_frames_8', 'enabled': '0', 'skip': '0'}]}]
    ^ ^ ^ pt(frame_based_results): (4 elements above this) pt.size = 62 Bytes (estimated) - list, Length: 4, (Line :323, @test_marking_of_videos(), mark_videos.py)
>>>Exited App<<< - pt.ex(): (Line :324, @test_marking_of_videos(), mark_videos.py)